// <copyright file="CloudVariables.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using CloudPrefs;

    /// <summary>
    /// Provides access to cloud variables registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudVariables
    {
        private static readonly CloudCurrencyInt s_coins = new CloudCurrencyInt("Coins", 0, false);

        public static int Coins
        {
            get { return s_coins.Value; }
            set { s_coins.Value = value; }
        }

        private static readonly CloudCurrencyInt s_trap = new CloudCurrencyInt("Trap", 3, false);

        public static int Trap
        {
            get { return s_trap.Value; }
            set { s_trap.Value = value; }
        }

        private static readonly CloudCurrencyInt s_tnt = new CloudCurrencyInt("Tnt", 3, false);

        public static int Tnt
        {
            get { return s_tnt.Value; }
            set { s_tnt.Value = value; }
        }

        private static readonly CloudCurrencyInt s_cidadela = new CloudCurrencyInt("Cidadela", 0, false);

        public static int Cidadela
        {
            get { return s_cidadela.Value; }
            set { s_cidadela.Value = value; }
        }

        private static readonly CloudCurrencyInt s_desertoSilencioso = new CloudCurrencyInt("DesertoSilencioso", 0, false);

        public static int DesertoSilencioso
        {
            get { return s_desertoSilencioso.Value; }
            set { s_desertoSilencioso.Value = value; }
        }

        private static readonly CloudCurrencyInt s_florestaNoturna = new CloudCurrencyInt("FlorestaNoturna", 0, false);

        public static int FlorestaNoturna
        {
            get { return s_florestaNoturna.Value; }
            set { s_florestaNoturna.Value = value; }
        }

        private static readonly CloudCurrencyInt s_minaAbandonada = new CloudCurrencyInt("MinaAbandonada", 0, false);

        public static int MinaAbandonada
        {
            get { return s_minaAbandonada.Value; }
            set { s_minaAbandonada.Value = value; }
        }

        private static readonly CloudCurrencyInt s_montanhasDoSul = new CloudCurrencyInt("MontanhasDoSul", 0, false);

        public static int MontanhasDoSul
        {
            get { return s_montanhasDoSul.Value; }
            set { s_montanhasDoSul.Value = value; }
        }

        private static readonly CloudCurrencyInt s_pantanoDosMortos = new CloudCurrencyInt("PantanoDosMortos", 0, false);

        public static int PantanoDosMortos
        {
            get { return s_pantanoDosMortos.Value; }
            set { s_pantanoDosMortos.Value = value; }
        }

        private static readonly CloudCurrencyInt s_valeDoDesespero = new CloudCurrencyInt("ValeDoDesespero", 0, false);

        public static int ValeDoDesespero
        {
            get { return s_valeDoDesespero.Value; }
            set { s_valeDoDesespero.Value = value; }
        }

        private static readonly CloudCurrencyInt s_vilarejoFantasma = new CloudCurrencyInt("VilarejoFantasma", 0, false);

        public static int VilarejoFantasma
        {
            get { return s_vilarejoFantasma.Value; }
            set { s_vilarejoFantasma.Value = value; }
        }

        private static readonly CloudCurrencyInt s_ads = new CloudCurrencyInt("Ads", 0, false);

        public static int Ads
        {
            get { return s_ads.Value; }
            set { s_ads.Value = value; }
        }
    }
}
